// src/db/indexedDB.ts
const DB_NAME = 'droneCompanionDB';
const DB_VERSION = 1;

// Define Object Store Names
const STORE_DRONES = 'drones';
const STORE_CHECKLISTS = 'checklists';
const STORE_FLIGHT_LOGS = 'flightLogs';
const STORE_ACHIEVEMENTS = 'achievements';

/**
 * Opens the IndexedDB database and creates object stores if needed.
 * @returns {Promise<IDBDatabase>} A promise that resolves with the database instance.
 */
export const openDB = (): Promise<IDBDatabase> => {
  return new Promise((resolve, reject) => {
    const request = indexedDB.open(DB_NAME, DB_VERSION);

    request.onupgradeneeded = (event: IDBVersionChangeEvent) => {
      const db = (event.target as IDBOpenDBRequest).result;
      console.log(`Upgrading database to version ${DB_VERSION}`);

      // Drones Store: Key path is 'id' (expecting a UUID generated by the app)
      if (!db.objectStoreNames.contains(STORE_DRONES)) {
        db.createObjectStore(STORE_DRONES, { keyPath: 'id' });
        console.log(`Created object store: ${STORE_DRONES}`);
      }

      // Checklists Store: Key path is 'id' (expecting a UUID generated by the app)
      if (!db.objectStoreNames.contains(STORE_CHECKLISTS)) {
        db.createObjectStore(STORE_CHECKLISTS, { keyPath: 'id' });
        console.log(`Created object store: ${STORE_CHECKLISTS}`);
      }

      // Flight Logs Store: Key path is 'id' (expecting a UUID generated by the app)
      if (!db.objectStoreNames.contains(STORE_FLIGHT_LOGS)) {
        const flightLogStore = db.createObjectStore(STORE_FLIGHT_LOGS, { keyPath: 'id' });
        // Add an index for potentially querying/sorting by date
        flightLogStore.createIndex('date_idx', 'date', { unique: false });
        console.log(`Created object store: ${STORE_FLIGHT_LOGS}`);
      }

      // Achievements Store: Key path is 'id' (e.g., 'FIRST_FLIGHT', '10_FLIGHTS')
      if (!db.objectStoreNames.contains(STORE_ACHIEVEMENTS)) {
        db.createObjectStore(STORE_ACHIEVEMENTS, { keyPath: 'id' });
        console.log(`Created object store: ${STORE_ACHIEVEMENTS}`);
      }
    };

    request.onerror = (event) => {
      console.error('Database error:', (event.target as IDBOpenDBRequest).error);
      reject(`Database error: ${(event.target as IDBOpenDBRequest).error}`);
    };

    request.onsuccess = (event) => {
      const db = (event.target as IDBOpenDBRequest).result;
      console.log(`Database ${DB_NAME} opened successfully.`);
      resolve(db);
    };
  });
};

// Optional: Export store names for easier use elsewhere
export {
    STORE_DRONES,
    STORE_CHECKLISTS,
    STORE_FLIGHT_LOGS,
    STORE_ACHIEVEMENTS
}; 